CREATE TABLE "admins" (
  "admin_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "suppliers" (
  "supplier_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "contact_no" varchar,
  "email" varchar,
  "address" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "medicines" (
  "medicine_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supplier_id" integer,
  "name" varchar NOT NULL,
  "generic_name" varchar,
  "manufacturer" varchar,
  "drug_type" varchar NOT NULL,
  "batch_no" varchar,
  "expiry_date" timestamp,
  "quantity" integer NOT NULL DEFAULT 0,
  "purchase_price" decimal(10,2) NOT NULL,
  "selling_price" decimal(10,2) NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "customers" (
  "customer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "contact_no" varchar,
  "email" varchar,
  "address" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "sales" (
  "sale_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" integer NOT NULL,
  "admin_id" integer NOT NULL,
  "total_amount" decimal(10,2) NOT NULL,
  "sale_date" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "sale_items" (
  "sale_item_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sale_id" integer NOT NULL,
  "medicine_id" integer NOT NULL,
  "medicine_name" varchar NOT NULL,
  "quantity" integer NOT NULL,
  "price" decimal(10,2) NOT NULL,
  "subtotal" decimal(10,2) NOT NULL
);

COMMENT ON COLUMN "medicines"."drug_type" IS 'tablet, capsule, syrup, injection, other';

ALTER TABLE "medicines" ADD FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sales" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sales" ADD FOREIGN KEY ("admin_id") REFERENCES "admins" ("admin_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale_items" ADD FOREIGN KEY ("sale_id") REFERENCES "sales" ("sale_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale_items" ADD FOREIGN KEY ("medicine_id") REFERENCES "medicines" ("medicine_id") DEFERRABLE INITIALLY IMMEDIATE;
